### ISSUE TITLE
downing data

### ISSUE THREAD

**Issue by suijua** [Reza-Zhu/SUES-200-Benchmark#4]
Hi ，Due to domestic network speed restrictions, data can be placed on Baidu Cloud Disk

您好！由于国内的网速限制，请问可以把数据集放在百度云上吗？万分感谢！

**Comment by Reza-Zhu** [comment]
百度网盘链接：
链接：https://pan.baidu.com/s/1mrd-7ADm57_OchAvO1XmNw 
提取码：p836 
天翼网盘（不限速）链接：
https://cloud.189.cn/t/yMnaEnR322Yj
提取码：veh7
