### ISSUE TITLE
Question about "Split Dataset".

### ISSUE THREAD

**Issue by KeepRunning2023** [Reza-Zhu/SUES-200-Benchmark#6]
Hi, thank you for sharing your work. 
It seems that there are some issues on the part of "Split Dataset". After I ran the code ''split_dataset.py'' according to the instructions, the "150" folder actually includes images of all heights, which also occurs in folders of other heights. I think the height folder should contain images of the corresponding height. Could you confirm if it's the code issue or if I misunderstood it. Thank you.
Look forward to your reply. : )

**Comment by Reza-Zhu** [comment]
It was my code issues, sorry. I have fixed it, try again.

**Comment by zdhgreat** [comment]
你好，我这边也出现了同样的问题，调用split_datasets.py的时候，出现了
FileNotFoundError: [Errno 2] No such file or directory: 'SUES-200-512x512/drone_view_512/150/0001'
是否是你数据位置问题亦或是文件读取的问题，还望解答

**Comment by Reza-Zhu** [comment]
是的，划分数据集的代码有问题，请clone最新版本的split_datasets.py后重试

**Comment by KeepRunning2023** [comment]
Thank you very much.
