### ISSUE TITLE
Question about weights

### ISSUE THREAD

**Issue by JinYu0516** [Reza-Zhu/SUES-200-Benchmark#7]
Hello!Thank you for your great work!
I don't know if there is a problem with my usage method, the results I got are far from what is in your paper, can you upload your weight file? Thank you so much!

您好！感谢您出色的工作！
不知道是不是我的使用方法有问题，我得出的结果数据和您论文中的相去甚远，可以上传一下您的权重文件吗？非常感谢！

**Comment by Reza-Zhu** [comment]
请问具体是哪几个模型的权重？

**Comment by JinYu0516** [comment]
ViT、VGG、SEResNet，这是我的邮箱：JinyuLiu2000@163.com，谢谢！
